name: Quality Assurance

on:
  workflow_call:

jobs:

  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up clang14
        run: |
          sudo apt-get install -y clang-14
      - name: Run cppcheck
        run: cppcheck client.cpp server.cpp || exit 1
      - name: Try to build apps with cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel -B build || exit 1
          cmake --build build || exit 1
#      yes tests will be here ... maybe somehow someday)
#      - name: Tests with ctest
#        run: ctest
